#!/usr/bin/make -f

.PHONY: DEFAULT_TARGET
DEFAULT_TARGET: gtksourceview2-install

include config.mk
include Makefile.zlib
include Makefile.libpng
include Makefile.libjpeg
include Makefile.freeglut
include Makefile.libtiff
include Makefile.bzip2
include Makefile.freetype
include Makefile.pixman
include Makefile.cairo
include Makefile.libiconv
include Makefile.gettext
include Makefile.libffi
include Makefile.glib
include Makefile.pango
include Makefile.gdk-pixbuf
include Makefile.atk
include Makefile.gtk2
include Makefile.xz-
include Makefile.libxml2
include Makefile.gtksourceview2
include Makefile.ocaml
include Makefile.findlib
include Makefile.camlp5
include Makefile.mingw-ocaml
include Makefile.lablgtk2
